"""Add secure dep task access grants

Revision ID: 0dace7b106cf
Revises: 066ccd71be93
Create Date: 2026-07-16 16:17:57.734010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dace7b106cf'
down_revision = '066ccd71be93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_access_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_task_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('recipient_email', sa.String(length=254), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workflow_task_id'], ['workflow_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('task_access_grants', schema=None) as batch_op:
        batch_op.create_index('ix_task_access_grants_task_state', ['workflow_task_id', 'revoked_at', 'consumed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_access_grants', schema=None) as batch_op:
        batch_op.drop_index('ix_task_access_grants_task_state')

    op.drop_table('task_access_grants')
    # ### end Alembic commands ###
