"""empty message

Revision ID: 35fab1a76164
Revises: cc52d172b803
Create Date: 2026-07-09 10:41:04.019070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35fab1a76164'
down_revision = 'cc52d172b803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('dep_id', sa.Integer(), nullable=False),
    sa.Column('dep_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('dep_id'),
    sa.UniqueConstraint('dep_name')
    )
    op.create_table('workflow_phase',
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dep_id', sa.Integer(), nullable=False),
    sa.Column('phase_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dep_id'], ['department.dep_id'], ),
    sa.PrimaryKeyConstraint('phase_id')
    )
    op.create_table('checklist_item',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_text', sa.String(length=150), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['workflow_phase.phase_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist_item')
    op.drop_table('workflow_phase')
    op.drop_table('department')
    # ### end Alembic commands ###
