"""case_table

Revision ID: 39a3d3659d8d
Revises: 
Create Date: 2026-07-08 11:11:36.752892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39a3d3659d8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offboarding_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(length=30), nullable=False),
    sa.Column('emp_name', sa.String(length=70), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('emp_designation', sa.String(), nullable=False),
    sa.Column('emp_department', sa.String(), nullable=False),
    sa.Column('last_day', sa.Date(), nullable=False),
    sa.Column('line_manager', sa.String(length=70), nullable=False),
    sa.Column('created_by', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number'),
    sa.UniqueConstraint('emp_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offboarding_case')
    # ### end Alembic commands ###
