"""empty message

Revision ID: 68b279cfd312
Revises: 430e02d26f99
Create Date: 2026-07-27 09:26:08.482082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b279cfd312'
down_revision = '430e02d26f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_departments_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_departments_name'))

    op.drop_table('employee_departments')
    # ### end Alembic commands ###
