"""empty message

Revision ID: 6dfc1e1aa3f1
Revises: 35fab1a76164
Create Date: 2026-07-09 11:42:36.026330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfc1e1aa3f1'
down_revision = '35fab1a76164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_email', sa.String(length=70), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['offboarding_case.id'], ),
    sa.ForeignKeyConstraint(['phase_id'], ['workflow_phase.phase_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('checklistresponse',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('workflow_task_id', sa.Integer(), nullable=False),
    sa.Column('checklist_item_id', sa.Integer(), nullable=False),
    sa.Column('response_status', sa.String(), nullable=False),
    sa.Column('not_applic_reason', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['offboarding_case.id'], ),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['checklist_item.item_id'], ),
    sa.ForeignKeyConstraint(['workflow_task_id'], ['workflow_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('response_id'),
    sa.UniqueConstraint('case_id'),
    sa.UniqueConstraint('workflow_task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklistresponse')
    op.drop_table('workflow_tasks')
    # ### end Alembic commands ###
