"""correct index name

Revision ID: 6e49f821eca5
Revises: 72ca45eb4245
Create Date: 2026-07-15 16:03:53.069020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e49f821eca5'
down_revision = '72ca45eb4245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offboarding_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boarding_case_employee_id'))
        batch_op.create_index('ix_offboarding_case_employee_id', ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offboarding_cases', schema=None) as batch_op:
        batch_op.drop_index('ix_offboarding_case_employee_id')
        batch_op.create_index(batch_op.f('ix_boarding_case_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###
