"""add indexes

Revision ID: 72ca45eb4245
Revises: b8c3e036fdd3
Create Date: 2026-07-15 15:19:04.491515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ca45eb4245'
down_revision = 'b8c3e036fdd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_case_created_at', ['case_id', 'created_at'], unique=False)

    with op.batch_alter_table('email_notifications', schema=None) as batch_op:
        batch_op.create_index('ix_email_notifications_case_status', ['case_id', 'status'], unique=False)
        batch_op.create_index('ix_email_notifications_task_type', ['workflow_task_id', 'notification_type'], unique=False)

    with op.batch_alter_table('offboarding_cases', schema=None) as batch_op:
        batch_op.create_index('ix_boarding_case_employee_id', ['employee_id'], unique=False)
        batch_op.create_index('ix_offboarding_case_current_phase_status', ['current_phase_id', 'status'], unique=False)
        batch_op.create_index('ix_offboarding_case_status_updated_at', ['status', 'updated_at'], unique=False)

    with op.batch_alter_table('workflow_tasks', schema=None) as batch_op:
        batch_op.create_index('ix_workflow_tasks_status_due_at', ['status', 'due_at'], unique=False)
        batch_op.create_unique_constraint('uq_workflow_tasks_case_phase', ['case_id', 'phase_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_tasks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_workflow_tasks_case_phase', type_='unique')
        batch_op.drop_index('ix_workflow_tasks_status_due_at')

    with op.batch_alter_table('offboarding_cases', schema=None) as batch_op:
        batch_op.drop_index('ix_offboarding_case_status_updated_at')
        batch_op.drop_index('ix_offboarding_case_current_phase_status')
        batch_op.drop_index('ix_boarding_case_employee_id')

    with op.batch_alter_table('email_notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_email_notifications_task_type')
        batch_op.drop_index('ix_email_notifications_case_status')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_case_created_at')

    # ### end Alembic commands ###
