"""add deduplication key column

Revision ID: b8c3e036fdd3
Revises: 905ff896573a
Create Date: 2026-07-14 12:01:08.580888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c3e036fdd3'
down_revision = '905ff896573a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deduplication_key', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['deduplication_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('deduplication_key')

    # ### end Alembic commands ###
