"""empty message

Revision ID: cc52d172b803
Revises: 39a3d3659d8d
Create Date: 2026-07-08 14:23:48.248398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc52d172b803'
down_revision = '39a3d3659d8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offboarding_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offboarding_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.VARCHAR(length=70), nullable=False))
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
