"""add department employee directory

Revision ID: dfef771cf82e
Revises: 0dace7b106cf
Create Date: 2026-07-22 08:24:44.376721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfef771cf82e'
down_revision = '0dace7b106cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('department_employees', schema=None) as batch_op:
        batch_op.create_index('ix_department_employees_department_active', ['department_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_department_employees_employee_code'), ['employee_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_employees_employee_code'))
        batch_op.drop_index('ix_department_employees_department_active')

    op.drop_table('department_employees')
    # ### end Alembic commands ###
